---
title: '0106-0111'
date: 2020-01-11 15:13:08
category: '2020-TIL'
---

> ## 0106

> ### Callbcak Hell (콜백지옥)

콜백 지옥이란 보통 비동기 프로그래밍시 발생하는 문제로서, 함수의 매개 변수로 넘겨지는 콜백 함수가 반복되어 코드의 들여쓰기 수준이 감당하기 힘들 정도로 깊어지는 현상을 말한다.

```js
step1(function(err, value1) {
  if (err) {
    console.log(err)
    return
  }
  step2(function(err, value2) {
    if (err) {
      console.log(err)
      return
    }
    step3(function(err, value3) {
      if (err) {
        console.log(err)
        return
      }
      step4(function(err, value4) {
        // 정신 건강을 위해 생략
      })
    })
  })
})
```

> ### **해결 방안**

#### (1) 콜백 함수를 분리

: 콜백 지옥이 발생하는 이유는 익명 함수를 연달아서 사용하기 때문이다. 익명 함수의 사용을 포기하고, 함수를 나눠 버리면 깔끔하다. 맨 위의 예를 다음과 같이 고칠 수 있다.

```js
step1(afterStep1)
function afterStep1(value1) {
  step2(afterStep2)
}
function afterStep2(value2) {
  step3(afterStep3)
}
// 생략
```

#### (2) Promise

: then이나 catch 내에서는 어떤 값을 리턴하거나, 다른 Promise를 리턴할 수도 있다. 또한 then과 catch는 계속 붙여서 쓸 수 있다.

Promise가 return되는 경우, 비동기 작업이 끝나 resolve나 reject가 호출될 때까지는 정지해 있다가, resolve나 reject가 실행되면 then이나 catch를 호출한다.

````js
somethingAsync(value1)
    .then((result) => {
        // 성공시 수행할 작업
    })
    .catch((error) => {
        // 실패시 수행할 작업
    });
    ```
````

#### (3) Async Function (async - await)

: await는 promise가 완료될 때까지 함수를 정지시키고, 완료되었을 경우 resolve되는 변수를 함수의 리턴 값인 것처럼 사용할 수 있게 한다. 만약 promise가 reject된 경우, try ~ catch 구문을 이용해 잡을 수 있다. await를 사용하기 위해서는 그 코드가 실행되는 함수가 async function으로 선언되어야 하며, async function에서 리턴되는 값은 promise에서 resolve하는 것으로 취급한다.

async - await를 사용함으로써, 동기 함수와 완전히 같은 방식으로 비동기 함수를 사용하면서, 비동기 함수의 장점을 잃지 않을 수 있다. 단점이라면 아직까지 콜백 방식이나 Promise를 직접 이용하는 것보다 퍼포먼스가 낮다는 점. 그러나 Async function이 모던 자바스크립트의 대세가 될 것임은 명백해 보인다.

```js
function f() {
  return somethingAsync(value1)
    .then(result => {
      // 성공시 수행할 작업
    })
    .catch(error => {
      // 실패시 수행할 작업
    })
}
```

```js
async function f() {
  try {
    var result = await somethingAsync(value1)
    // 성공시 수행할 작업
  } catch (error) {
    // 실패시 수행할 작업
  }
}
```
